import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import ClientWrapper from "@/components/cleint-wrappers/client-wrapper";

import { ProjectProvider } from "./context/projectContext";
import { TaskProvider } from "./context/taskContext";
import { EventProvider } from "@/app/context/eventContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className="bg-gray-100 text-gray-900">
        <ProjectProvider>
            <TaskProvider>
                <EventProvider>
                    <ClientWrapper>{children}</ClientWrapper>
                </EventProvider>
            </TaskProvider>
        </ProjectProvider>
        </body>
        </html>
    );
}
