import type { Metadata } from "next";
import './globals.css';
import { ReactNode } from 'react';
import ClientDrawer from "@/components/client-drawer/component";
import { ProjectProvider } from './context/projectContext';
import { TaskProvider } from './context/taskContext';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-gray-100 text-gray-900">
                <ProjectProvider>
                    <TaskProvider>
                        <ClientDrawer>
                            {children}
                        </ClientDrawer>
                    </TaskProvider>
                </ProjectProvider>
            </body>
        </html>
    );
}